import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Button from '../components/Button.js';
import Text from '../components/Text.js';
import Footer from '../components/Footer.js';





export default function Home() {
  return (
    <div className={styles.container}>
      <div className={styles.bgWrap}>
        <Image
          alt="travel"
          src="/../public/background.jpg"
          layout="fill"
          objectFit="cover"
          quality={100}
        />
      </div>
      <Head>
        <title>Coping Strategies</title>
        <meta name="description" content="Generated by Linden" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Take a deep breath and ...
        </h1>
        <Text />  
        <Footer />
        <p className={styles.end}>Made with
          <span role="img" aria-label="heart"> ❤️ </span>
          &nbsp;by Linden Schrage
        </p>
      </main>
    </div>

  )
}
