import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Button from '../components/Button.js';
import Text from '../components/Text.js';
import Footer from '../components/Footer.js';




export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Coping Strategies</title>
        <meta name="description" content="Generated by Linden" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Take a deep breath and ...
        </h1>
        <Text />  
        <Footer />
      </main>
      
      

    </div>
  )
}
